### ISSUE TITLE
inap galaxy workflow problem

### ISSUE THREAD

**Issue by aslangabriel** [yedeng-lab/iNAP#1]
The web tools didn't offer FTP for large files transfer. Would you like to share me with the whole galaxy workflow so that I can run it on local host ?

**Comment by KaiFeng007** [comment]
Hi, iNAP supports large files online. Basically, the large files can be uploaded directly. We do not need FTP site to transfer files. 

If your input files are out of 2000 OTUs/Species, we suggest to decrease the numbers or run the provided methods (SparCC, Spiec-Easi, eLSA etc.) on local supercomputators.

Best, 

> The web tools didn't offer FTP for large files transfer. Would you like to share me with the whole galaxy workflow so that I can run it on local host ?
