### ISSUE TITLE
Integrated Network Analysis Pipeline 

### ISSUE THREAD

**Issue by Rainjie-afk** [yedeng-lab/iNAP#2]
Dear developers:
When I tried to use  [iNAP](http://[mem.rcees.ac.cn](http://mem.rcees.ac.cn:8081/):8081/) found that the server is down.
![image](https://github.com/yedeng-lab/iNAP/assets/68232446/effbb2de-9fe5-4a6b-a65b-68f68bff6e5b)

Can it be fixed or not?
Best regards.

**Comment by KaiFeng007** [comment]
Hi, Sorry for this inconvience. Our server met some problems and still need some days to fix. We will let you know once the iNAP is back. @Rainjie-afk

**Comment by KaiFeng007** [comment]
Hi, @Rainjie-afk 

The iNAP website is updated now, and please visit our new website: [https://inap.denglab.org.cn/](https://inap.denglab.org.cn/)  . Let me know if you still have problems.

Best regards
