### ISSUE TITLE
Inquiry Regarding Sample Quantity

### ISSUE THREAD

**Issue by fhdbqr** [yedeng-lab/iNAP#3]
Hello, although the paper mentions the need for 8 or more samples, I still want to ask if it's possible to construct a IDENAP with only 5-6 samples, or if there are alternative methods available? Laboratory experiments rarely involve 8 parallel designs. Thank you.

**Comment by KaiFeng007** [comment]
Hi, You can finish the first step 'majority selection' in iNAP, and then finish the correlation calculations in your local computers. Just follow the codes/scripts in this [iNAP Github page](https://github.com/yedeng-lab/iNAP). After doing this, upload the correlation and P-value matrix file into iNAP, usually it is fine to conduct the following steps.

**Comment by fhdbqr** [comment]
Thank you very much for your reply. I'll give it a try.
